######################################################################
# Automatically generated by qmake (3.0) ?? ??? 13 08:50:06 2018
######################################################################

TEMPLATE = app
TARGET = system_valder
INCLUDEPATH += .

# Input
SOURCES += test.cpp

# CONFIG += console 

LIBS += -lpthread libwsock32 libws2_32
